apiVersion: v1
kind: Pod
metadata:
  name: testclient
  namespace: demo
spec:
  containers:
  - name: kafka
    image: confluentinc/cp-kafka:4.1.1-2
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
