apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
spec:
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: thomsch98/kafdrop
        env:
        - name: ZK_HOSTS
          value: kafka-zookeeper:2181
        - name: LISTEN
          value: "9000"
        ports:
        - name: http
          containerPort: 9000
        livenessProbe:
          httpGet:
            path: /
            port: 9000
        readinessProbe:
          httpGet:
            path: /
            port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
spec:
  ports:
  - name: http
    port: 9000
    targetPort: http
  selector:
    app: kafka-manager
