// Code generated by protoc-gen-go. DO NOT EDIT.
// source: products.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Product struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Longtext             string   `protobuf:"bytes,4,opt,name=longtext,proto3" json:"longtext,omitempty"`
	SmallImageURL        string   `protobuf:"bytes,5,opt,name=smallImageURL,proto3" json:"smallImageURL,omitempty"`
	LargeImageURL        string   `protobuf:"bytes,6,opt,name=largeImageURL,proto3" json:"largeImageURL,omitempty"`
	Price                float32  `protobuf:"fixed32,7,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_f2ec7fe1796e93e8, []int{0}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetLongtext() string {
	if m != nil {
		return m.Longtext
	}
	return ""
}

func (m *Product) GetSmallImageURL() string {
	if m != nil {
		return m.SmallImageURL
	}
	return ""
}

func (m *Product) GetLargeImageURL() string {
	if m != nil {
		return m.LargeImageURL
	}
	return ""
}

func (m *Product) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func init() {
	proto.RegisterType((*Product)(nil), "pb.Product")
}

func init() { proto.RegisterFile("products.proto", fileDescriptor_products_f2ec7fe1796e93e8) }

var fileDescriptor_products_f2ec7fe1796e93e8 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x4f,
	0x29, 0x4d, 0x2e, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xba,
	0xcc, 0xc8, 0xc5, 0x1e, 0x00, 0x11, 0x16, 0x12, 0xe2, 0x62, 0x29, 0x2d, 0xcd, 0x4c, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x44, 0xb8, 0x58, 0x4b, 0x32, 0x4b, 0x72, 0x52,
	0x25, 0x98, 0xc0, 0x82, 0x10, 0x8e, 0x90, 0x02, 0x17, 0x77, 0x4a, 0x6a, 0x71, 0x72, 0x51, 0x66,
	0x41, 0x49, 0x66, 0x7e, 0x9e, 0x04, 0x33, 0x58, 0x0e, 0x59, 0x48, 0x48, 0x8a, 0x8b, 0x23, 0x27,
	0x3f, 0x2f, 0xbd, 0x24, 0xb5, 0xa2, 0x44, 0x82, 0x05, 0x2c, 0x0d, 0xe7, 0x0b, 0xa9, 0x70, 0xf1,
	0x16, 0xe7, 0x26, 0xe6, 0xe4, 0x78, 0xe6, 0x26, 0xa6, 0xa7, 0x86, 0x06, 0xf9, 0x48, 0xb0, 0x82,
	0x15, 0xa0, 0x0a, 0x82, 0x54, 0xe5, 0x24, 0x16, 0xa5, 0xa7, 0xc2, 0x55, 0xb1, 0x41, 0x54, 0xa1,
	0x08, 0x82, 0xdc, 0x57, 0x50, 0x94, 0x99, 0x9c, 0x2a, 0xc1, 0xae, 0xc0, 0xa8, 0xc1, 0x14, 0x04,
	0xe1, 0x24, 0xb1, 0x81, 0x3d, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x21, 0x2b, 0x2d,
	0xf2, 0x00, 0x00, 0x00,
}
